services:
  - type: web
    name: barber-backend
    runtime: python
    rootDir: backend
    plan: free
    healthCheckPath: /health
    buildCommand: bash render-build.sh
    startCommand: .venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        value: https://barber-fron-kxb7codgp-jamshidjalolovs-projects.vercel.app
      - key: CORS_ALLOWED_ORIGIN_REGEX
        value: https://.*\.vercel\.app
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: POETRY_VIRTUALENVS_IN_PROJECT
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: barber-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: barber-db
    plan: free
    databaseName: barbershop
    user: barbershop_user
